name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        directory: ["Lab-1"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.yaml') }}
          path: |
            .spago
            output

      - name: Set up Node toolchain
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install NPM dependencies
        run: npm install -g spago@next purescript@latest purs-tidy

      - name: cd ${{ matrix.directory }} directory
        run: cd ${{ matrix.directory }}

      - name: Install NPM dependencies
        run: npm install

      - name: Check formatting
        run: purs-tidy check "src/**/*.purs"

      - name: Install Spago dependencies
        run: spago install

      - name: Build the project
        run: spago build

      - name: Run tests
        run: spago test
